#!/usr/bin/env python3
"""
PyTorch-based Kaggle Submission Generator for BirdCLEF+ 2026.

Generates a Jupyter notebook that:
  - Loads PyTorch model weights from our training agent
  - Processes audio using librosa (CPU-only, <90 min budget)
  - Runs multi-label inference on test_soundscapes
  - Produces submission.csv in required Kaggle format

Usage:
    python generate_pytorch_submission.py [--model path/to/model.pt] [--output submission.ipynb]
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

try:
    import nbformat
    from nbformat.v4 import new_notebook, new_code_cell, new_markdown_cell
    _NBFORMAT_AVAILABLE = True
except ImportError:
    _NBFORMAT_AVAILABLE = False


# Notebook cells
_CELLS: list[tuple[str, str]] = [
    ("markdown", "# BirdCLEF+ 2026 Track B - PyTorch Submission\nAuto-generated by the Autonomous Research Agent\n\nMulti-label classification of 234 bird species from audio spectrograms."),
    
    ("code", """import os, time, warnings, json
warnings.filterwarnings("ignore")
import numpy as np
import pandas as pd
import librosa
import torch
import torch.nn as nn

SUBMISSION_START = time.time()
MAX_RUNTIME_S = 90 * 60

def time_remaining():
    return MAX_RUNTIME_S - (time.time() - SUBMISSION_START)

print(f"Submission started. Runtime budget: {MAX_RUNTIME_S/60:.0f} min")
print(f"PyTorch: {torch.__version__}, CUDA: {torch.cuda.is_available()}")
"""),

    ("code", """INPUT_DIR = "/kaggle/input"
TEST_DIR = os.path.join(INPUT_DIR, "birdclef-2026", "test_soundscapes")
SAMPLE_SUB = os.path.join(INPUT_DIR, "birdclef-2026", "sample_submission.csv")
MODEL_WEIGHTS = "/kaggle/input/birdclef-pytorch-weights/best_model.pt"

print(f"Test dir: {TEST_DIR}")
print(f"Model weights: {MODEL_WEIGHTS}")
"""),

    ("code", """sample_sub = pd.read_csv(SAMPLE_SUB)
SPECIES_COLS = [c for c in sample_sub.columns if c != "row_id"]
NUM_SPECIES = len(SPECIES_COLS)
print(f"Species to predict: {NUM_SPECIES}")
"""),

    ("code", """SR = 22050
DURATION = 5.0
N_MELS = 128
N_FFT = 2048
HOP_LENGTH = 512
FMIN = 50
FMAX = 14000
TOP_DB = 80.0
TARGET_H = 128
TARGET_W = 216

def audio_to_melspec(waveform, sr=SR):
    mel = librosa.feature.melspectrogram(
        y=waveform, sr=sr, n_fft=N_FFT, hop_length=HOP_LENGTH,
        n_mels=N_MELS, fmin=FMIN, fmax=FMAX,
    )
    log_mel = librosa.power_to_db(mel, ref=np.max, top_db=TOP_DB)
    log_mel = (log_mel + TOP_DB) / TOP_DB
    return log_mel.astype(np.float32)

def pad_or_trim(spec, target_h=TARGET_H, target_w=TARGET_W):
    spec = spec[:, :target_w] if spec.shape[1] > target_w else spec
    spec = np.pad(spec, ((0, 0), (0, max(0, target_w - spec.shape[1]))))
    spec = spec[:target_h, :] if spec.shape[0] > target_h else spec
    spec = np.pad(spec, ((0, max(0, target_h - spec.shape[0])), (0, 0)))
    return spec

def load_chunks(filepath, chunk_duration=DURATION):
    try:
        y, _ = librosa.load(filepath, sr=SR, mono=True)
    except Exception as e:
        print(f"Warning: failed to load {filepath}: {e}")
        return
    chunk_len = int(chunk_duration * SR)
    for start in range(0, len(y), chunk_len):
        chunk = y[start : start + chunk_len]
        if len(chunk) < chunk_len // 4:
            break
        if len(chunk) < chunk_len:
            chunk = np.pad(chunk, (0, chunk_len - len(chunk)))
        spec = audio_to_melspec(chunk)
        spec = pad_or_trim(spec)
        yield spec[np.newaxis, ...]

print("Audio preprocessing ready.")
"""),

    ("code", """class BirdCLEFModel(nn.Module):
    def __init__(self, num_species=NUM_SPECIES):
        super().__init__()
        self.conv_layers = nn.Sequential(
            nn.Conv2d(1, 32, 3, padding=1),
            nn.BatchNorm2d(32),
            nn.ReLU(),
            nn.Conv2d(32, 64, 3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(),
        )
        self.pool = nn.AdaptiveAvgPool2d((1, 1))
        self.classifier = nn.Sequential(
            nn.Linear(64, 128),
            nn.ReLU(),
            nn.Linear(128, num_species),
        )
    
    def forward(self, x):
        x = self.conv_layers(x)
        x = self.pool(x).view(x.size(0), -1)
        x = torch.sigmoid(self.classifier(x))
        return x

device = torch.device("cpu")
model = BirdCLEFModel(num_species=NUM_SPECIES).to(device)
model.eval()

if os.path.exists(MODEL_WEIGHTS):
    state = torch.load(MODEL_WEIGHTS, map_location=device)
    model.load_state_dict(state)
    print(f"Loaded model weights from {MODEL_WEIGHTS}")
else:
    print(f"WARNING: Model weights not found. Using random initialization.")

print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")
"""),

    ("code", """BATCH_SIZE = 4
results = []
test_files = sorted([
    f for f in os.listdir(TEST_DIR)
    if f.endswith((".ogg", ".wav", ".mp3"))
]) if os.path.isdir(TEST_DIR) else []

print(f"Test files found: {len(test_files)}")

for file_idx, fname in enumerate(test_files):
    if time_remaining() < 300:
        print("Approaching time limit, stopping.")
        break
    
    if (file_idx + 1) % 10 == 0:
        print(f"  [{file_idx+1}/{len(test_files)}] {time_remaining()/60:.1f} min remaining")
    
    fpath = os.path.join(TEST_DIR, fname)
    stem = os.path.splitext(fname)[0]
    
    chunks = list(load_chunks(fpath))
    if not chunks:
        continue
    
    all_preds = []
    for batch_start in range(0, len(chunks), BATCH_SIZE):
        batch_end = min(batch_start + BATCH_SIZE, len(chunks))
        batch_specs = np.stack(chunks[batch_start:batch_end], axis=0)
        batch_tensor = torch.from_numpy(batch_specs).to(device)
        
        with torch.no_grad():
            preds = model(batch_tensor).cpu().numpy()
        
        all_preds.append(preds)
    
    all_preds = np.concatenate(all_preds, axis=0)
    
    for chunk_idx, pred in enumerate(all_preds):
        end_sec = int((chunk_idx + 1) * DURATION)
        row_id = f"{stem}_{end_sec}"
        row = {"row_id": row_id}
        row.update(dict(zip(SPECIES_COLS, pred.tolist())))
        results.append(row)

print(f"Inference complete. Total rows: {len(results)}")
print(f"Time remaining: {time_remaining()/60:.1f} min")
"""),

    ("code", """if results:
    submission = pd.DataFrame(results)
    print(f"Submission shape: {submission.shape}")
else:
    print("No results. Using sample submission with zeros.")
    submission = pd.read_csv(SAMPLE_SUB)
    for col in SPECIES_COLS:
        submission[col] = 0.0

submission = submission[["row_id"] + SPECIES_COLS]
submission.to_csv("submission.csv", index=False)
print(f"Saved submission.csv ({submission.shape[0]} rows)")
"""),
]


def build_notebook() -> "nbformat.NotebookNode":
    """Build the Jupyter notebook object."""
    nb = new_notebook()
    cells = []
    for cell_type, source in _CELLS:
        if cell_type == "markdown":
            cells.append(new_markdown_cell(source))
        else:
            cells.append(new_code_cell(source))
    nb.cells = cells
    nb.metadata["kernelspec"] = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }
    return nb


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate PyTorch BirdCLEF+ 2026 submission notebook."
    )
    parser.add_argument(
        "--output", type=Path, default=Path("submission_pytorch.ipynb"),
        help="Output notebook path.",
    )
    parser.add_argument(
        "--model", type=Path, default=None,
        help="Path to model weights (for reference).",
    )
    args = parser.parse_args()
    
    if _NBFORMAT_AVAILABLE:
        nb = build_notebook()
        args.output.write_text(nbformat.writes(nb, version=4), encoding="utf-8")
        print(f"✓ Notebook written to: {args.output}")
        print(f"  Cells: {len(nb.cells)}")
    else:
        print("Error: nbformat not installed. Install with: pip install nbformat")
    
    if args.model and args.model.exists():
        size_mb = args.model.stat().st_size / 1e6
        print(f"Model weights: {args.model} ({size_mb:.1f} MB)")


if __name__ == "__main__":
    main()
