"""
Kaggle Submission Notebook Generator for BirdCLEF+ 2026 (Track B).

Generates a Jupyter notebook that:
  - Loads and preprocesses audio clips using torchaudio
  - Loads the best trained PyTorch model weights (.pt)
  - Runs inference on 5-second chunks within a 90-minute CPU budget
  - Produces a submission.csv in the required Kaggle format

Usage
-----
    python generate_submission.py [--weights path/to/best_model.pt]
                                  [--model simple_cnn_torch]
                                  [--output submission_notebook.ipynb]

The generated notebook is self-contained and safe to upload to the
Kaggle submission environment.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

try:
    import nbformat
    from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook
    _NBFORMAT_AVAILABLE = True
except ImportError:
    _NBFORMAT_AVAILABLE = False


# ---------------------------------------------------------------------------
# Notebook cells  (PyTorch inference, config-aligned)
# ---------------------------------------------------------------------------

_CELLS: list[tuple[str, str]] = [
    ("markdown", """\
# BirdCLEF+ 2026 – Track B Submission Notebook
**Auto-generated by the Autonomous Research Agent**

- Multi-label classification of bird species (PyTorch)
- CPU-only inference, ≤ 90 minutes
- mel-spectrogram pipeline (torchaudio, SR=32 000 Hz, N_MELS=128)
"""),

    ("code", """\
# ── Dependencies ────────────────────────────────────────────────────────────
import os
import time
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import torch
import torchaudio
import torchaudio.transforms as T

SUBMISSION_START = time.time()
MAX_RUNTIME_S = 90 * 60

def time_remaining() -> float:
    return MAX_RUNTIME_S - (time.time() - SUBMISSION_START)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {DEVICE}")
print(f"Runtime budget: {MAX_RUNTIME_S / 60:.0f} min")
"""),

    ("code", """\
# ── Paths ────────────────────────────────────────────────────────────────────
INPUT_DIR  = "/kaggle/input"
TEST_DIR   = os.path.join(INPUT_DIR, "birdclef-2026", "test_soundscapes")
TRAIN_CSV  = os.path.join(INPUT_DIR, "birdclef-2026", "train.csv")
SAMPLE_SUB = os.path.join(INPUT_DIR, "birdclef-2026", "sample_submission.csv")
TAXONOMY   = os.path.join(INPUT_DIR, "birdclef-2026", "taxonomy.csv")

# Model weights — point at your best checkpoint
MODEL_WEIGHTS = "/kaggle/input/birdclef-model-weights/best_model.pt"
MODEL_NAME    = "simple_cnn_torch"   # "simple_cnn_torch" or "efficientnet_torch"

print("Input files:", os.listdir(INPUT_DIR))
"""),

    ("code", """\
# ── Species list ─────────────────────────────────────────────────────────────
sample_sub = pd.read_csv(SAMPLE_SUB)
SPECIES_COLS = [c for c in sample_sub.columns if c != "row_id"]
NUM_SPECIES  = len(SPECIES_COLS)
print(f"Species columns: {NUM_SPECIES}")
"""),

    ("code", """\
# ── Audio parameters ─────────────────────────────────────────────────────────
SR           = 32_000
CLIP_DURATION = 5.0
CLIP_SAMPLES  = int(SR * CLIP_DURATION)   # 160 000
N_MELS        = 128
N_FFT         = 1024
HOP_LENGTH    = 512
F_MIN         = 50.0
F_MAX         = 14_000.0
TOP_DB        = 80.0
TIME_FRAMES   = (CLIP_SAMPLES // HOP_LENGTH) + 1   # 313

_mel_transform = T.MelSpectrogram(
    sample_rate=SR, n_fft=N_FFT, hop_length=HOP_LENGTH,
    n_mels=N_MELS, f_min=F_MIN, f_max=F_MAX,
)
_amplitude_to_db = T.AmplitudeToDB(top_db=TOP_DB)


def waveform_to_melspec(waveform: torch.Tensor) -> torch.Tensor:
    \"\"\"(1, samples) → (1, N_MELS, TIME_FRAMES) normalised to [0,1].\"\"\"
    mel = _mel_transform(waveform)
    log_mel = _amplitude_to_db(mel)
    return ((log_mel + TOP_DB) / TOP_DB).float()


def load_soundscape_chunks(filepath: str):
    \"\"\"Yield (chunk_idx, mel_spec_tensor) for each 5-second chunk.\"\"\"
    try:
        waveform, orig_sr = torchaudio.load(filepath)
    except Exception as exc:
        print(f"  Warning: failed to load {filepath}: {exc}")
        return

    # Mix to mono
    if waveform.shape[0] > 1:
        waveform = waveform.mean(dim=0, keepdim=True)

    # Resample if needed
    if orig_sr != SR:
        waveform = T.Resample(orig_freq=orig_sr, new_freq=SR)(waveform)

    total = waveform.shape[-1]
    idx = 0
    start = 0
    while start < total:
        end = start + CLIP_SAMPLES
        chunk = waveform[:, start:end]
        if chunk.shape[-1] < CLIP_SAMPLES // 4:
            break   # skip very short tail chunks
        if chunk.shape[-1] < CLIP_SAMPLES:
            chunk = torch.nn.functional.pad(chunk, (0, CLIP_SAMPLES - chunk.shape[-1]))
        yield idx, waveform_to_melspec(chunk)
        idx += 1
        start = end

print("Preprocessing helpers ready.")
"""),

    ("code", """\
# ── Model definition ─────────────────────────────────────────────────────────
import torch.nn as nn


class SimpleCNN(nn.Module):
    def __init__(self, num_classes=NUM_SPECIES):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=3, padding=1),
            nn.BatchNorm2d(32), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128), nn.ReLU(),
            nn.AdaptiveAvgPool2d((1, 1)),
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128, 256), nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes),
        )

    def forward(self, x):
        return torch.sigmoid(self.classifier(self.features(x)))


def build_model(name: str) -> nn.Module:
    if name == "simple_cnn_torch":
        return SimpleCNN(num_classes=NUM_SPECIES)
    raise ValueError(f"Unknown model: {name!r}")


model = build_model(MODEL_NAME)

if os.path.exists(MODEL_WEIGHTS):
    state_dict = torch.load(MODEL_WEIGHTS, map_location=DEVICE)
    model.load_state_dict(state_dict)
    print(f"Loaded weights from {MODEL_WEIGHTS}")
else:
    print("WARNING: Model weights not found — using random weights for demo.")

model = model.to(DEVICE)
model.eval()
print(f"Model ready: {MODEL_NAME}")
"""),

    ("code", """\
# ── Inference loop ───────────────────────────────────────────────────────────
BATCH_SIZE = 32

results = []

test_files = sorted([
    f for f in os.listdir(TEST_DIR)
    if f.endswith(".ogg") or f.endswith(".wav")
]) if os.path.isdir(TEST_DIR) else []

print(f"Test files found: {len(test_files)}")

for fname in test_files:
    if time_remaining() < 300:
        print("WARNING: approaching time limit, stopping inference early.")
        break

    fpath = os.path.join(TEST_DIR, fname)
    stem  = os.path.splitext(fname)[0]

    chunks = list(load_soundscape_chunks(fpath))
    if not chunks:
        continue

    # Batch inference
    for batch_start in range(0, len(chunks), BATCH_SIZE):
        batch_chunks = chunks[batch_start : batch_start + BATCH_SIZE]
        idxs   = [c[0] for c in batch_chunks]
        specs  = torch.stack([c[1] for c in batch_chunks]).to(DEVICE)

        with torch.no_grad():
            preds = model(specs).cpu().numpy()

        for i, chunk_idx in enumerate(idxs):
            end_sec = int((chunk_idx + 1) * CLIP_DURATION)
            row_id  = f"{stem}_{end_sec}"
            row = {"row_id": row_id}
            row.update(dict(zip(SPECIES_COLS, preds[i].tolist())))
            results.append(row)

print(f"Inference complete. Total rows: {len(results)}")
print(f"Time remaining: {time_remaining() / 60:.1f} min")
"""),

    ("code", """\
# ── Build submission DataFrame ───────────────────────────────────────────────
if results:
    submission = pd.DataFrame(results)
else:
    # Fallback: use sample submission with zeros
    submission = pd.read_csv(SAMPLE_SUB)
    for col in SPECIES_COLS:
        submission[col] = 0.0

submission = submission[["row_id"] + SPECIES_COLS]
submission.to_csv("submission.csv", index=False)
print("submission.csv written:", submission.shape)
submission.head()
"""),

    ("markdown", """\
## Submission complete
`submission.csv` has been saved. Upload it to the BirdCLEF+ 2026 competition page.
"""),
]


# ---------------------------------------------------------------------------
# Notebook builder
# ---------------------------------------------------------------------------

def build_notebook():
    """Construct the Jupyter notebook object."""
    nb = new_notebook()
    cells = []
    for cell_type, source in _CELLS:
        if cell_type == "markdown":
            cells.append(new_markdown_cell(source))
        else:
            cells.append(new_code_cell(source))
    nb.cells = cells
    nb.metadata["kernelspec"] = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }
    nb.metadata["language_info"] = {"name": "python", "version": "3.10.0"}
    return nb


def build_notebook_fallback() -> str:
    """Return the notebook as raw JSON when nbformat is not installed."""
    cells_json = []
    for cell_type, source in _CELLS:
        ct = "code" if cell_type == "code" else "markdown"
        cell = {"cell_type": ct, "metadata": {}, "source": source}
        if ct == "code":
            cell["outputs"] = []
            cell["execution_count"] = None
        cells_json.append(cell)

    nb = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.10.0"},
        },
        "cells": cells_json,
    }
    return json.dumps(nb, indent=2)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a BirdCLEF+ 2026 Kaggle submission notebook (PyTorch).",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--output", type=Path, default=Path("submission_notebook.ipynb"),
        help="Output path for the generated notebook.",
    )
    args = parser.parse_args()

    out_path: Path = args.output

    if _NBFORMAT_AVAILABLE:
        nb = build_notebook()
        out_path.write_text(
            nbformat.writes(nb, version=4), encoding="utf-8"
        )
        print(f"Notebook written to: {out_path}  ({len(nb.cells)} cells)")
    else:
        raw = build_notebook_fallback()
        out_path.write_text(raw, encoding="utf-8")
        print(
            f"Notebook written to: {out_path} (nbformat not installed; raw JSON used)\n"
            "Install nbformat: pip install nbformat"
        )


if __name__ == "__main__":
    main()
